# Default values for kubecost-s3-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: "kubecost-s3-exporter"

image: "udid/kubecost_cid:0.1.0"
imagePullPolicy: Always

cronJob:
  name: "kubecost-s3-exporter"
  schedule: "@midnight"

serviceAccount:
  create: true
  name: "kubecost-s3-exporter"
  role: "" # Example: arn:aws:iam::<account_id>:role/<role_name>

env:
  - name: "S3_BUCKET_NAME"
    value: "kubecost-data"
  - name: "KUBECOST_API_ENDPOINT"
    value: "http://kubecost-cost-analyzer.kubecost:9090" # Change to your Kubecost endpoint if necessary
  - name: "CLUSTER_NAME"
    value: "cluster-one" # Change to your EKS cluster name
  - name: "GRANULARITY"
    value: "hourly"
  - name: "LABELS"
    value: "" # Comma-separated list of labels. Example: "app, chart"
  - name: "PYTHONUNBUFFERED"
    value: "1"